apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-service
  name: social-graph-service
spec:
  ports:
    - name: "8191"
      port: 8191
      targetPort: 8191
    - name: "8194"
      port: 8194
      targetPort: 8194
  selector:
    io.kompose.service: social-graph-service
status:
  loadBalancer: {}
