spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootauth
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/