spring:
  application:
    name: Auth-Service
  datasource:
    url: ${BLOSSOM_AUTH_DB}
    username: ${BLOSSOM_AUTH_DB_USERNAME}
    password: ${BLOSSOM_AUTH_DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${BLOSSOM_EMAIL_USERNAME}
    password: ${BLOSSOM_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${BLOSSOM_KAFKA}
    topics: user-resource-event-post, user-resource-event-social, user-resource-event-activity, user-resource-event-feed, user-resource-event-message
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: event:org.blossom.model.ResourceEvent
vendor:
  frontend:
    callback-url-validate: ${BLOSSOM_VALIDATE_CALLBACK}
    callback-url-recover: ${BLOSSOM_RECOVER_CALLBACK}
jwt:
  secret: ${BLOSSOM_JWT_SECRET}
  duration: ${BLOSSOM_JWT_DURATION}
  refresh:
    duration: ${BLOSSOM_JWT_REFRESH_DURATION}
server:
  port: ${BLOSSOM_AUTH_PORT}
grpc:
  server:
    name: Image-Service
  client:
    awaitTerminationInSeconds: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/