spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootauth
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${BLOSSOM_EMAIL_USERNAME}
    password: ${BLOSSOM_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    topics: resource-event-posts, resource-event-social
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: event:org.blossom.model.ResourceEvent
vendor:
  frontend:
    callback-url: ${BLOSSOM_CALLBACK}
jwt:
  secret: ${BLOSSOM_JWT_SECRET}
  refresh: ${BLOSSOM_JWT_REFRESH}
server:
  port: 9564
grpc:
  server:
    name: Image-Service
  client:
    awaitTerminationInSeconds: 10
    withDeadlineAfterInSeconds: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/