spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootauth
  sql:
    init:
      mode: always
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/