spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootauth
  flyway:
    baseline-on-migrate: true
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  refresh: 86400000
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/