spring:
  application:
    name: Notification-Service
  data:
    mongodb:
      host: ${BLOSSOM_NOTIFICATION_DB_HOST}
      port: ${BLOSSOM_NOTIFICATION_DB_PORT}
      database: ${BLOSSOM_NOTIFICATION_DB_NAME}
  kafka:
    bootstrap-servers: ${BLOSSOM_KAFKA}
    consumer:
      group-id: notificationListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
  redis:
    host: localhost
    port: 6388
broker:
  host: ${BLOSSOM_NOTIFICATION_BROKER_HOST}
  port: ${BLOSSOM_NOTIFICATION_BROKER_PORT}
  username: ${BLOSSOM_NOTIFICATION_BROKER_USERNAME}
  password: ${BLOSSOM_NOTIFICATION_BROKER_PASSWORD}
server:
  port: ${BLOSSOM_NOTIFICATION_PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/