spring:
  application:
    name: Notification-Service
  data:
    mongodb:
      host: localhost
      port: 6386
      database: notification-db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificationListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
server:
  port: 8210
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/