spring:
  data:
    redis:
      repositories:
        enabled: false
  application:
    name: Activity-Service
  datasource:
    url: ${BLOSSOM_ACTIVITY_DB}
    username: ${BLOSSOM_ACTIVITY_DB_USERNAME}
    password: ${BLOSSOM_ACTIVITY_DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  redis:
    host: ${BLOSSOM_ACTIVITY_CACHE_HOST}
    port: ${BLOSSOM_ACTIVITY_CACHE_PORT}
  kafka:
    bootstrap-servers: ${BLOSSOM_KAFKA}
    consumer:
      group-id: activityListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
grpc:
  server:
    port: ${BLOSSOM_ACTIVITY_GRPC_PORT}
    awaitTerminationInSeconds: 10
server:
  port: ${BLOSSOM_ACTIVITY_PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/