apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: image-service
  name: image-service
spec:
  ports:
    - name: "8185"
      port: 8185
      targetPort: 8185
    - name: "8188"
      port: 8188
      targetPort: 8188
  selector:
    io.kompose.service: image-service
status:
  loadBalancer: {}
