version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  message-broker:
    image: bernardofmf/blossom-custom-rabbitmq-stomp:latest
    container_name: message-broker
    ports:
      - "9093:15672"
      - "9094:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=${ROOT_USER_RELAY}
      - RABBITMQ_DEFAULT_PASS=${ROOT_PASSWORD_RELAY}

  notification-broker:
    image: bernardofmf/blossom-custom-rabbitmq-stomp:latest
    container_name: notification-broker
    ports:
      - "9095:15672"
      - "9096:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=${ROOT_USER_RELAY}
      - RABBITMQ_DEFAULT_PASS=${ROOT_PASSWORD_RELAY}

  activity-service-cache:
    image: redis:7.2.3-bookworm
    container_name: activity-service-cache
    ports:
      - "6377:6379"
    restart: always

  post-service-cache:
    image: redis:7.2.3-bookworm
    container_name: post-service-cache
    ports:
      - "6379:6379"
    restart: always

  auth-service-db:
    image: postgres:16.1
    container_name: auth-service-db
    ports:
      - "6380:5432"
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=${ROOT_USER}
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./auth-service-db:/data/postgres
    restart: always

  activity-service-db:
    image: postgres:16.1
    container_name: activity-service-db
    ports:
      - "6381:5432"
    environment:
      - POSTGRES_DB=activity-db
      - POSTGRES_USER=${ROOT_USER}
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./activity-service-db:/data/postgres
    restart: always

  social-graph-service-db:
    image: neo4j:5.12.0-community-bullseye
    container_name: social-graph-service-db
    ports:
      - "6382:7474"
      - "6383:7687"
    volumes:
      - ./social-graph-service-db:/data
    restart: always

  feed-service-db:
    image: cassandra:latest
    container_name: feed-service-db
    ports:
      - "6384:9042"
    volumes:
      - ./feed-service-db:/var/lib/cassandra
    restart: always

  post-service-db:
    image: mongo:7.0
    container_name: post-service-db
    ports:
      - "6385:27017"
    volumes:
      - ./post-service-db:/data/db
    restart: always

  notification-service-db:
    image: mongo:7.0
    container_name: notification-service-db
    ports:
      - "6386:27017"
    volumes:
      - ./notification-service-db:/data/db
    restart: always

  message-service-db:
    image: postgres:16.1
    container_name: message-service-db
    ports:
      - "6387:5432"
    environment:
      - POSTGRES_DB=message-db
      - POSTGRES_USER=${ROOT_USER}
      - POSTGRES_PASSWORD=${ROOT_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./message-service-db:/data/postgres
    restart: always

  discovery-server:
    image: bernardofmf/blossom-discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: bernardofmf/blossom-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8181"
    expose:
      - "8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_GATEWAY_PORT=8181
    depends_on:
      - discovery-server

  image-service:
    image: bernardofmf/blossom-image-service:latest
    container_name: image-service
    ports:
      - "8185:8185"
      - "8188:8188"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_IMAGE_PORT=8185
      - BLOSSOM_IMAGE_GRPC_PORT=8188
      - BLOSSOM_S3_MOCK=true
      - BLOSSOM_S3_REGION=${S3_REGION}
      - BLOSSOM_S3_BUCKET=${S3_BUCKET}
      - BLOSSOM_S3_PATH=/
    depends_on:
      - discovery-server
      - api-gateway

  auth-service:
    image: bernardofmf/blossom-auth-service:latest
    container_name: auth-service
    ports:
      - "8182:8182"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_AUTH_DB=jdbc:postgresql://auth-service-db:5432/auth-db
      - BLOSSOM_AUTH_DB_USERNAME=${ROOT_USER}
      - BLOSSOM_AUTH_DB_PASSWORD=${ROOT_PASSWORD}
      - BLOSSOM_EMAIL_USERNAME=${EMAIL_USERNAME}
      - BLOSSOM_EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_CALLBACK=http://localhost:100/callbackUrl
      - BLOSSOM_JWT_SECRET=${JWT_SECRET}
      - BLOSSOM_JWT_REFRESH=${JWT_REFRESH}
      - BLOSSOM_AUTH_PORT=8182
    depends_on:
      - auth-service-db
      - discovery-server
      - api-gateway
      - image-service

  post-service:
    image: bernardofmf/blossom-post-service:latest
    container_name: post-service
    ports:
      - "8213:8213"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_POST_DB_HOST=post-service-db
      - BLOSSOM_POST_DB_PORT=27017
      - BLOSSOM_POST_DB_NAME=post-db
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_POST_CACHE_HOST=post-service-cache
      - BLOSSOM_POST_CACHE_PORT=6379
      - BLOSSOM_POST_PORT=8213
    depends_on:
      - post-service-db
      - post-service-cache
      - discovery-server
      - api-gateway
      - image-service

  activity-service:
    image: bernardofmf/blossom-activity-service:latest
    container_name: activity-service
    ports:
      - "8197:8197"
      - "8201:8201"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_ACTIVITY_DB=jdbc:postgresql://activity-service-db:5432/activity-db
      - BLOSSOM_ACTIVITY_DB_USERNAME=${ROOT_USER}
      - BLOSSOM_ACTIVITY_DB_PASSWORD=${ROOT_PASSWORD}
      - BLOSSOM_ACTIVITY_CACHE_HOST=activity-service-cache
      - BLOSSOM_ACTIVITY_CACHE_PORT=6379
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_ACTIVITY_GRPC_PORT=8201
      - BLOSSOM_ACTIVITY_PORT=8197
    depends_on:
      - activity-service-db
      - activity-service-cache
      - discovery-server
      - api-gateway
      - auth-service
      - post-service

  social-graph-service:
    image: bernardofmf/blossom-social-graph-service:latest
    container_name: social-graph-service
    ports:
      - "8191:8191"
      - "8194:8194"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_SOCIAL_DB=bolt://social-graph-service-db:7687
      - BLOSSOM_SOCIAL_DB_USERNAME=${ROOT_USER}
      - BLOSSOM_SOCIAL_DB_PASSWORD=${ROOT_PASSWORD}
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_SOCIAL_PORT=8191
      - BLOSSOM_SOCIAL_GRPC_PORT=8194
    depends_on:
      - social-graph-service-db
      - discovery-server
      - api-gateway
      - auth-service

  feed-service:
    image: bernardofmf/blossom-feed-service:latest
    container_name: feed-service
    ports:
      - "8204:8204"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_FEED_DB_SPACE=feedSpace
      - BLOSSOM_FEED_DB_HOST=feed-service-db
      - BLOSSOM_FEED_DB_PORT=9042
      - BLOSSOM_FEED_DB_DATACENTER=datacenter1
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_FEED_PORT=8204
    depends_on:
      - feed-service-db
      - discovery-server
      - api-gateway
      - auth-service
      - social-graph-service
      - post-service

  message-service:
    image: bernardofmf/blossom-message-service:latest
    container_name: message-service
    ports:
      - "8207:8207"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_MESSAGE_DB=jdbc:postgresql://message-service-db:5432/message-db
      - BLOSSOM_MESSAGE_DB_USERNAME=${ROOT_USER}
      - BLOSSOM_MESSAGE_DB_PASSWORD=${ROOT_PASSWORD}
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_MESSAGE_BROKER_HOST=message-broker
      - BLOSSOM_MESSAGE_BROKER_PORT=61613
      - BLOSSOM_MESSAGE_BROKER_USERNAME=${ROOT_USER_RELAY}
      - BLOSSOM_MESSAGE_BROKER_PASSWORD=${ROOT_PASSWORD_RELAY}
      - BLOSSOM_MESSAGE_PORT=8207
    depends_on:
      - message-service-db
      - message-broker
      - discovery-server
      - api-gateway
      - auth-service
      - social-graph-service

  notification-service:
    image: bernardofmf/blossom-notification-service:latest
    container_name: notification-service
    ports:
      - "8210:8210"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BLOSSOM_NOTIFICATION_DB_HOST=notification-service-db
      - BLOSSOM_NOTIFICATION_DB_PORT=27017
      - BLOSSOM_NOTIFICATION_DB_NAME=notification-db
      - BLOSSOM_KAFKA=broker:29092
      - BLOSSOM_NOTIFICATION_BROKER_HOST=notification-broker
      - BLOSSOM_NOTIFICATION_BROKER_PORT=61613
      - BLOSSOM_NOTIFICATION_BROKER_USERNAME=${ROOT_USER_RELAY}
      - BLOSSOM_NOTIFICATION_BROKER_PASSWORD=${ROOT_PASSWORD_RELAY}
      - BLOSSOM_NOTIFICATION_PORT=8210
    depends_on:
      - notification-service-db
      - notification-broker
      - discovery-server
      - api-gateway
      - auth-service
      - social-graph-service