version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  message-broker:
    image: stomp-rabbitmq
    container_name: message-broker
    ports:
      - "9093:15672"
      - "9094:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=message
      - RABBITMQ_DEFAULT_PASS=rootmessage

  notification-broker:
    image: stomp-rabbitmq
    container_name: notification-broker
    ports:
      - "9095:15672"
      - "9096:61613"
    environment:
      - RABBITMQ_DEFAULT_USER=notification
      - RABBITMQ_DEFAULT_PASS=rootnotification

  activity-service-cache:
    image: redis:latest
    container_name: activity-service-cache
    ports:
      - "6377:6379"

  feed-service-cache:
    image: redis:latest
    container_name: feed-service-cache
    ports:
      - "6378:6379"

  post-service-cache:
    image: redis:latest
    container_name: post-service-cache
    ports:
      - "6379:6379"

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    ports:
      - "6380:5432"
    environment:
      - POSTGRES_PASSWORD=rootauth

  activity-service-db:
    image: postgres:latest
    container_name: activity-service-db
    ports:
      - "6381:5432"
    environment:
      - POSTGRES_PASSWORD=rootactivity

  social-graph-service-db:
    image: neo4j
    container_name: social-graph-service-db
    ports:
      - "6382:7474"
      - "6383:7687"

  feed-service-db:
    image: cassandra:latest
    container_name: feed-service-db
    ports:
      - "6384:9042"

  post-service-db:
    image: mongo:latest
    container_name: post-service-db
    ports:
      - "6385:27017"

  notification-service-db:
    image: mongo:latest
    container_name: notification-service-db
    ports:
      - "6386:27017"

  message-service-db:
    image: postgres:latest
    container_name: message-service-db
    ports:
      - "6387:5432"
    environment:
      - POSTGRES_PASSWORD=rootmessage