apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
    - name: "8181"
      protocol: TCP
      port: 8181
      targetPort: 8181
      nodePort: 30100
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}
