apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: message-broker
  name: message-broker
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 15672
    - name: "9094"
      port: 9094
      targetPort: 61613
  selector:
    io.kompose.service: message-broker
status:
  loadBalancer: {}
