apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-broker
  name: notification-broker
spec:
  ports:
    - name: "9095"
      port: 9095
      targetPort: 15672
    - name: "9096"
      port: 9096
      targetPort: 61613
  selector:
    io.kompose.service: notification-broker
status:
  loadBalancer: {}
