apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: post-service
  name: post-service
spec:
  ports:
    - name: "8213"
      port: 8213
      targetPort: 8213
  selector:
    io.kompose.service: post-service
status:
  loadBalancer: {}
