spring:
  application:
    name: Post-Service
  data:
    mongodb:
      host: ${BLOSSOM_POST_DB_HOST}
      port: ${BLOSSOM_POST_DB_PORT}
      database: ${BLOSSOM_POST_DB_NAME}
  kafka:
    bootstrap-servers: ${BLOSSOM_KAFKA}
    topics: post-resource-event-feed, post-resource-event-activity
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: event:org.blossom.model.ResourceEvent
    consumer:
      group-id: postListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
  redis:
    host: ${BLOSSOM_POST_CACHE_HOST}
    port: ${BLOSSOM_POST_CACHE_PORT}
server:
  port: ${BLOSSOM_POST_PORT}
grpc:
  server:
    names:
      image: Image-Service
      activity: Activity-Service
  client:
    awaitTerminationInSeconds: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/