spring:
  application:
    name: Auth-Service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: resource-event
    consumer:
      group-id: searchListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/