spring:
  application:
    name: Feed-Service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: postListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
grpc:
  server:
    names:
      social: Social-Service
      activity: Activity-Service
  client:
    awaitTerminationInSeconds: 10
server:
  port: 9460
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/