apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: message-service
  name: message-service
spec:
  ports:
    - name: "8207"
      port: 8207
      targetPort: 8207
  selector:
    io.kompose.service: message-service
status:
  loadBalancer: {}
