eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: Image-Service
grpc:
  server:
    port: 8188
    awaitTerminationInSeconds: 10
aws:
  region: ${BLOSSOM_S3_REGION}
  s3:
    mock: true
    path: ${BLOSSOM_S3_PATH}
    buckets:
      imageBucket: ${BLOSSOM_S3_BUCKET}
server:
  port: 8185