eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-server.default.svc.cluster.local:8761/eureka