spring:
  application:
    name: Image-Service
grpc:
  server:
    port: ${BLOSSOM_IMAGE_GRPC_PORT}
    awaitTerminationInSeconds: 10
aws:
  region: ${BLOSSOM_S3_REGION}
  s3:
    mock: ${BLOSSOM_S3_MOCK}
    path: ${BLOSSOM_S3_PATH}
    buckets:
      imageBucket: ${BLOSSOM_S3_BUCKET}
server:
  port: ${BLOSSOM_IMAGE_PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/