apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-service
  name: notification-service
spec:
  ports:
    - name: "8210"
      port: 8210
      targetPort: 8210
  selector:
    io.kompose.service: notification-service
status:
  loadBalancer: {}
