apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: feed-service
  name: feed-service
spec:
  ports:
    - name: "8204"
      port: 8204
      targetPort: 8204
  selector:
    io.kompose.service: feed-service
status:
  loadBalancer: {}
