spring:
  application:
    name: Social-Graph-Service
  neo4j:
    uri: ${BLOSSOM_SOCIAL_DB}
    authentication:
      username: ${BLOSSOM_SOCIAL_DB_USERNAME}
      password: ${BLOSSOM_SOCIAL_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${BLOSSOM_KAFKA}
    topic: social-follow-resource-event-message
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: event:org.blossom.model.ResourceEvent
    consumer:
      group-id: socialListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
server:
  port: ${BLOSSOM_SOCIAL_PORT}
grpc:
  server:
    port: ${BLOSSOM_SOCIAL_GRPC_PORT}
    awaitTerminationInSeconds: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/