spring:
  application:
    name: Social-Graph-Service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: social-graph-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: socialListenerId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.blossom.json.CustomResourceEventDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.blossom.model"
            type:
              mapping: event:org.blossom.model.ResourceEvent
server:
  port: 9565
grpc:
  server:
    port: 0
    awaitTerminationInSeconds: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/