name: compile-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: build with maven
      run: mvn -B package
    - name: log in to docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: build docker images
      run: |
        for module in env.MODULES; do
          cd ./$module
          docker build -t blossom-$module .
          docker tag blossom-$module:latest blossom-$module:$(date +"%Y%m%d%H%M%S")
          docker push blossom-$module
          cd ..
        done